create extension if not exists pgcrypto with schema extensions;
create extension if not exists vector with schema public;

create table if not exists public.archivos_fuente (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  storage_path text not null,
  tipo text,
  created_at timestamptz default now(),
  activo boolean default true
);

create table if not exists public.documentos_kb (
  id uuid primary key default gen_random_uuid(),
  contenido text not null,
  metadata jsonb,
  embedding vector(384),
  archivo_id uuid references public.archivos_fuente(id) on delete cascade
);

create table if not exists public.capacitaciones (
  id uuid primary key default gen_random_uuid(),
  titulo text not null,
  descripcion text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  publicada boolean not null default false
);

create table if not exists public.capacitacion_modulos (
  id uuid primary key default gen_random_uuid(),
  capacitacion_id uuid not null references public.capacitaciones(id) on delete cascade,
  titulo text not null,
  descripcion text,
  orden integer not null,
  created_at timestamptz not null default now(),
  preguntas jsonb,
  porcentaje_aprobacion integer,
  duracion_maxima_minutos integer,
  cantidad_preguntas_a_mostrar integer,
  constraint uq_capacitacion_modulo_orden unique (capacitacion_id, orden)
);

create table if not exists public.modulo_recursos (
  id uuid primary key default gen_random_uuid(),
  modulo_id uuid not null references public.capacitacion_modulos(id) on delete cascade,
  tipo text not null check (tipo = any (array['archivo', 'youtube'])),
  titulo text,
  orden integer not null,
  youtube_url text,
  archivo_url text,
  archivo_path text,
  archivo_nombre text,
  extension text,
  created_at timestamptz not null default now(),
  constraint uq_modulo_recurso_orden unique (modulo_id, orden)
);

create table if not exists public.certificaciones (
  id uuid primary key default gen_random_uuid(),
  capacitacion_id uuid not null unique references public.capacitaciones(id) on delete cascade,
  titulo text not null,
  descripcion text,
  preguntas jsonb not null default '[]'::jsonb,
  porcentaje_aprobacion integer not null check (porcentaje_aprobacion >= 0 and porcentaje_aprobacion <= 100),
  duracion_maxima_minutos integer not null check (duracion_maxima_minutos > 0),
  created_at timestamptz not null default now(),
  cantidad_preguntas_examen integer not null check (cantidad_preguntas_examen > 0)
);

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  nombre text not null unique
);

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  imagen_url text,
  id_categoria bigint references public.categorias(id) on delete set null
);

create table if not exists public.user_progress (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  modulo_id uuid references public.capacitacion_modulos(id) on delete cascade,
  recurso_id uuid,
  aprobado boolean default true,
  updated_at timestamptz default timezone('utc'::text, now()),
  constraint user_progress_user_id_recurso_id_key unique (user_id, recurso_id)
);

create table if not exists public.exam_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  capacitacion_id uuid references public.capacitaciones(id) on delete cascade,
  modulo_id uuid references public.capacitacion_modulos(id) on delete cascade,
  certificacion_id uuid references public.certificaciones(id) on delete cascade,
  tipo_examen text not null check (tipo_examen = any (array['modulo', 'final'])),
  intento_numero integer not null,
  max_intentos integer not null default 3,
  estado text not null default 'iniciado' check (estado = any (array['iniciado', 'completado', 'abandonado'])),
  porcentaje numeric,
  aprobado boolean default false,
  fecha_inicio timestamptz not null default now(),
  fecha_fin timestamptz,
  created_at timestamptz default now(),
  respuestas_detalle jsonb not null default '[]'::jsonb,
  duracion_segundos integer,
  constraint exam_attempts_unique unique (
    user_id,
    tipo_examen,
    capacitacion_id,
    modulo_id,
    certificacion_id,
    intento_numero
  )
);

create table if not exists public.certification_requests (
  id uuid primary key default gen_random_uuid(),
  certification_id uuid not null references public.certificaciones(id) on delete cascade,
  capacitacion_id uuid references public.capacitaciones(id) on delete cascade,
  certification_title text not null,
  capacitacion_title text,
  requester_name text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status = any (array['pending', 'approved', 'rejected'])),
  rejection_reason text,
  exam_percentage numeric,
  exam_approved_at timestamptz,
  requested_at timestamptz not null default now(),
  reviewed_at timestamptz,
  exam_attempt_id uuid references public.exam_attempts(id) on delete set null
);

create table if not exists public.progreso_recursos (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  capacitacion_id uuid not null references public.capacitaciones(id) on delete cascade,
  modulo_id uuid not null references public.capacitacion_modulos(id) on delete cascade,
  recurso_id uuid not null references public.modulo_recursos(id) on delete cascade,
  completado boolean not null default false,
  completado_en timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint progreso_recursos_unique unique (user_id, recurso_id)
);

create index if not exists idx_capacitacion_modulos_capacitacion_id on public.capacitacion_modulos (capacitacion_id);
create index if not exists idx_modulo_recursos_modulo_id on public.modulo_recursos (modulo_id);
create index if not exists idx_certificaciones_capacitacion_id on public.certificaciones (capacitacion_id);
create index if not exists idx_documentos_kb_archivo_id on public.documentos_kb (archivo_id);
create index if not exists idx_productos_id_categoria on public.productos (id_categoria);
create index if not exists certification_requests_certification_id_idx on public.certification_requests (certification_id);
create index if not exists certification_requests_capacitacion_id_idx on public.certification_requests (capacitacion_id);
create index if not exists certification_requests_exam_attempt_id_idx on public.certification_requests (exam_attempt_id);
create index if not exists certification_requests_status_idx on public.certification_requests (status);
create index if not exists certification_requests_user_id_idx on public.certification_requests (user_id);
create index if not exists exam_attempts_capacitacion_id_idx on public.exam_attempts (capacitacion_id);
create index if not exists exam_attempts_certificacion_id_idx on public.exam_attempts (certificacion_id);
create index if not exists exam_attempts_modulo_id_idx on public.exam_attempts (modulo_id);
create index if not exists progreso_recursos_capacitacion_id_idx on public.progreso_recursos (capacitacion_id);
create index if not exists progreso_recursos_modulo_id_idx on public.progreso_recursos (modulo_id);
create index if not exists progreso_recursos_recurso_id_idx on public.progreso_recursos (recurso_id);
create index if not exists user_progress_modulo_id_idx on public.user_progress (modulo_id);
create index if not exists documentos_kb_embedding_idx on public.documentos_kb using hnsw (embedding vector_cosine_ops);

create or replace function public.is_admin()
returns boolean
language sql
stable
set search_path = ''
as $$
  select coalesce((select auth.jwt()) -> 'app_metadata' ->> 'role', '') = 'admin';
$$;

create or replace function public.is_authenticated()
returns boolean
language sql
stable
set search_path = ''
as $$
  select (select auth.role()) = 'authenticated';
$$;

create or replace function public.buscar_contexto_kb(
  query_embedding vector(384),
  match_threshold double precision,
  match_count integer
)
returns table(contenido text, metadata jsonb, similitud double precision)
language plpgsql
stable
set search_path = ''
as $$
begin
  return query
  select
    d.contenido,
    d.metadata,
    1 - (d.embedding OPERATOR(public.<=>) query_embedding) as similitud
  from public.documentos_kb d
  inner join public.archivos_fuente a on a.id = d.archivo_id
  where a.activo = true
    and d.embedding is not null
    and 1 - (d.embedding OPERATOR(public.<=>) query_embedding) > match_threshold
  order by d.embedding OPERATOR(public.<=>) query_embedding asc
  limit match_count;
end;
$$;

revoke execute on function public.is_admin() from anon, authenticated;
grant execute on function public.buscar_contexto_kb(vector, double precision, integer) to anon, authenticated, service_role;
grant execute on function public.is_authenticated() to anon, authenticated, service_role;

alter table public.archivos_fuente enable row level security;
alter table public.documentos_kb enable row level security;
alter table public.capacitaciones enable row level security;
alter table public.capacitacion_modulos enable row level security;
alter table public.modulo_recursos enable row level security;
alter table public.certificaciones enable row level security;
alter table public.categorias enable row level security;
alter table public.productos enable row level security;
alter table public.user_progress enable row level security;
alter table public.exam_attempts enable row level security;
alter table public.certification_requests enable row level security;
alter table public.progreso_recursos enable row level security;

grant select on public.categorias, public.productos to anon, authenticated;
grant select on public.archivos_fuente, public.documentos_kb to authenticated;
grant select on public.capacitaciones, public.capacitacion_modulos, public.modulo_recursos, public.certificaciones to authenticated;
grant select, insert, update, delete on all tables in schema public to service_role;
grant select, insert, update, delete on public.capacitaciones, public.capacitacion_modulos, public.modulo_recursos, public.certificaciones to authenticated;
grant select, insert, update, delete on public.archivos_fuente, public.documentos_kb to authenticated;
grant select, insert, update on public.user_progress, public.exam_attempts, public.certification_requests, public.progreso_recursos to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

create policy "archivos_fuente_admin_all" on public.archivos_fuente
  for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "archivos_fuente_authenticated_read" on public.archivos_fuente
  for select to authenticated using (true);

create policy "documentos_kb_admin_all" on public.documentos_kb
  for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "documentos_kb_authenticated_read" on public.documentos_kb
  for select to authenticated using (true);

create policy "capacitaciones_admin_all" on public.capacitaciones
  for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "capacitaciones_authenticated_read" on public.capacitaciones
  for select to authenticated using (public.is_authenticated());

create policy "capacitacion_modulos_admin_all" on public.capacitacion_modulos
  for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "capacitacion_modulos_authenticated_read" on public.capacitacion_modulos
  for select to authenticated using (public.is_authenticated());

create policy "modulo_recursos_admin_all" on public.modulo_recursos
  for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "modulo_recursos_authenticated_read" on public.modulo_recursos
  for select to authenticated using (public.is_authenticated());

create policy "certificaciones_admin_all" on public.certificaciones
  for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "certificaciones_authenticated_read" on public.certificaciones
  for select to authenticated using (public.is_authenticated());

create policy "categorias_public_read" on public.categorias
  for select to anon, authenticated using (true);
create policy "categorias_admin_all" on public.categorias
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "productos_public_read" on public.productos
  for select to anon, authenticated using (true);
create policy "productos_admin_all" on public.productos
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "user_progress_select_own" on public.user_progress
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "user_progress_insert_own" on public.user_progress
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "user_progress_update_own" on public.user_progress
  for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create policy "exam_attempts_select_own_or_admin" on public.exam_attempts
  for select to authenticated using (((select auth.uid()) = user_id) or public.is_admin());
create policy "exam_attempts_insert_own" on public.exam_attempts
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "exam_attempts_update_own" on public.exam_attempts
  for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create policy "certification_requests_select_own_or_admin" on public.certification_requests
  for select to authenticated using (((select auth.uid()) = user_id) or public.is_admin());
create policy "certification_requests_insert_own" on public.certification_requests
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "certification_requests_update_admin" on public.certification_requests
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "progreso_recursos_select_own" on public.progreso_recursos
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "progreso_recursos_insert_own" on public.progreso_recursos
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "progreso_recursos_update_own" on public.progreso_recursos
  for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  (
    'formacion-archivos',
    'formacion-archivos',
    true,
    104857600,
    array[
      'application/pdf',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'image/jpeg',
      'image/png',
      'video/mp4'
    ]
  ),
  (
    'kb-files',
    'kb-files',
    false,
    20971520,
    array['application/pdf', 'text/markdown', 'text/plain']
  )
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "formacion_storage_select_authenticated" on storage.objects
  for select to authenticated using (bucket_id = 'formacion-archivos');
create policy "formacion_storage_insert_admin" on storage.objects
  for insert to authenticated with check (bucket_id = 'formacion-archivos' and public.is_admin());
create policy "formacion_storage_update_admin" on storage.objects
  for update to authenticated using (bucket_id = 'formacion-archivos' and public.is_admin()) with check (bucket_id = 'formacion-archivos' and public.is_admin());
create policy "formacion_storage_delete_admin" on storage.objects
  for delete to authenticated using (bucket_id = 'formacion-archivos' and public.is_admin());

create policy "kb_storage_admin_all" on storage.objects
  for all to authenticated using (bucket_id = 'kb-files' and public.is_admin()) with check (bucket_id = 'kb-files' and public.is_admin());
